### ISSUE TITLE
Using vertical bar "|" for unions makes the package incompatible to python < 3.10 but 3.9 is still listed

### ISSUE THREAD

**Issue by SimonStier** [pyiron/pyiron_snippets#23]
Usage:
https://github.com/pyiron/pyiron_snippets/blob/7a4fe2ad467dbe4059b774763e6263a59ad72324/pyiron_snippets/resources.py#L37

Version compatibility:
https://github.com/pyiron/pyiron_snippets/blob/7a4fe2ad467dbe4059b774763e6263a59ad72324/pyproject.toml#L20

See also: https://stackoverflow.com/questions/64615988/what-does-vertical-bar-pipe-in-function-arguments-type-annotations-mean

**Comment by liamhuber** [comment]
Hi @SimonStier, welcome to snippets!

Good catch 🚀 I believe we can get backwards compatibility for this syntax using `from __future__ import annotations` in the relevant files, and this is my preferred solution. 

Unfortunately, our CI suite [has a bug preventing our python versions from being correctly read](https://github.com/pyiron/actions/issues/123), so we're not actually getting 3.9 test coverage. Hence having missed the bug in this file. Fixing that bug is my top priority today, but this one is so quick I made a little PR just now. Once I get the CI bug fixed and the version updated here, we'll get a final confirmation that this (or a related) bug is not hiding anywhere else in snippets, and I'll release a patch.
